### ISSUE TITLE
数据集mosei

### ISSUE THREAD

**Issue by Xu-ys** [MANLP-suda/HHMPN#4]
你好，可以提供一下你的mosei的数据集吗？谢谢

**Comment by MANLP-suda** [comment]
链接数据丢失了，我这几天重新上传下。 如果你着急的话，也可以去官网下载自己处理下。

**Comment by Xu-ys** [comment]
> 链接数据丢失了，我这几天重新上传下。 如果你着急的话，也可以去官网下载自己处理下。

好的，谢谢你！

**Comment by Xu-ys** [comment]
> 链接数据丢失了，我这几天重新上传下。 如果你着急的话，也可以去官网下载自己处理下。

好的！谢谢

**Comment by Xu-ys** [comment]
> > 链接数据丢失了，我这几天重新上传下。 如果你着急的话，也可以去官网下载自己处理下。
> 
> 好的！谢谢

你好，你上传送的文件好像少了train_valid_test.pt等文件！

**Comment by MANLP-suda** [comment]
已经在重新上传了，前几天上传的数据没处理过。

**Comment by Xu-ys** [comment]
> 已经在重新上传了，前几天上传的数据没处理过。

好的！十分的感谢你。

**Comment by Xu-ys** [comment]
> 已经在重新上传了，前几天上传的数据没处理过。

**Comment by Xu-ys** [comment]
你好！我在预训练的时候显示IsADirectoryError: [Errno 21] Is a directory: '../data/rcv1/RCV1-V2/text_train'。

**Comment by MANLP-suda** [comment]
你没有设置新路径吧，路径设置为mosei数据集，或者你可以先看下数据读取的代码，数据输入格式应该就知道了

**Comment by Xu-ys** [comment]
好的！谢谢你



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月6日(星期天) 晚上10:02
收件人: "MANLP-suda/HHMPN";
抄送: "State&nbsp;change";
主题: Re: [MANLP-suda/HHMPN] 数据集mosei (Issue #4)





 
你没有设置新路径吧，路径设置为mosei数据集，或者你可以先看下数据读取的代码，数据输入格式应该就知道了
 
&mdash;

**Comment by Xu-ys** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "徐杨胜"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月7日(星期一) 下午5:03
***@***.***&gt;;

主题:&nbsp;数据集



你好！请问你在MMESGN Transformer-based Label Set Generation for Multi-modal Multi-label Emotion Detection文章中使用的mosei（mosei_emotion_aligned_60.pkl）数据集是下面这个数据集吗？

如果不是！麻烦你给一个下载连接！十分感谢你。

**Comment by mdswyz** [comment]
你好我想问一下这个train_valid_test.pt的数据集文件是如何预处理生成的，如果我想转别的数据集（比如MELD,IEMOCAP）有没有工具箱可以进行处理，感谢！

**Comment by MANLP-suda** [comment]
mosei数据有开源的包处理的， https://github.com/A2Zadeh/CMU-MultimodalSDK  你可以看下这个能否适合你
